---

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf
            backup=yes

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update

#- name: Restart Supervisor
#  supervisorctl: name={{ application_name }} state=restarted

